#https://github.com/xoxxel/dns-only-clash

mixed-port: 7890
allow-lan: false
external-controller: 127.0.0.1:55027
mode: rule
log-level: info

dns:
  enable: true
  listen: 0.0.0.0:53
  enhanced-mode: fake-ip
  nameserver:
    - https://1.1.1.1/dns-query
    - https://8.8.8.8/dns-query
  fallback:
    - https://1.0.0.1/dns-query
    - https://9.9.9.9/dns-query

tun:
  enable: true
  stack: system
  dns-hijack:
    - any:53
